### ISSUE TITLE
MPE controller

### ISSUE THREAD

**Issue by jpcima** [rncbc/qmidictl#4]
Hi. I would appreciate a lot if qmidictl can have offer some sort of multi-touch, piano-like interface for Android tablets.

If MIDI Polyphonic Expression support is provided, it provides help for a developer who wants to develop MPE spec support on Linux synths, which is currently near to inexistent.
(Multi-touch tablet is the cheapest and available form of controller for implementing the MPE)

If this is fine, I can contribute my help for such a feature.

**Comment by rncbc** [comment]
multi-touch is already a thing in v0.5.5+ ...

however i'm not sure whether MPE is here relevant... QmidiCtl has no piano-keyboard whatever interface: it is and has been just a _proof-of-concept_ for raw-MIDI over UDP/IP multicast on a wired and/or wireless LAN.

you probably are asking for a multi-touch general purpose touch-surface controller (like TouchDAW, TouchOSC or as maybe plc's VMPK) and probably having tilt, velocity and/or pressure detection where available.

not dismissing an otherwise great idea, rather way out of scope the qmidictl _propects_ :)
cheers

**Comment by jpcima** [comment]
No problem. I'm going to derive this into its own software, I wanted just to ask first.

It's on my vague roadmap to have RTP-Midi/AppleMidi, as a more reliable kind of protocol.
For a start, I will be fine with the *proof of concept*.

Thanks
